name: Publish package builds

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of release. patch or minor (major if breaking)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish-browser-agent-core:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: build
        run: npm run ci-build 

      - name: "Version and publish"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          npx lerna version ${{ github.event.inputs.release_type }} --no-changelog --yes

          npx lerna publish from-package --yes
