name: Tests

on:
  pull_request:
    types: [review_requested, edited, syncronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: build
        run: npm run ci-build

      - name: lint
        run: npm run lint
  
