name: Tests

on:
  pull_request:
    types: [review_requested, edited, syncronize]

jobs:
  all-browsers-unit:
    runs-on: ubuntu-latest
    container: node:14
    env:
      NEWRELIC_ENVIRONMENT: ci
      JIL_SAUCE_LABS_USERNAME: ${{ secrets.JIL_SAUCE_LABS_USERNAME }}
      JIL_SAUCE_LABS_ACCESS_KEY: ${{ secrets.JIL_SAUCE_LABS_ACCESS_KEY }}
      NEW_RELIC_LICENSE_KEY: ${{ secrets.JIL_NODE_NEW_RELIC_LICENSE_KEY }}
      BUILD_NUMBER: PR${{ github.event.number }}-unit-${{ github.run_number }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: build
        run: npm run ci-build

      - name: run tests
        run: node ./tools/jil/bin/cli.js -f merged -b *@* -s -t 85000 --unit-only --concurrent=20
