name: Tests - Lint

on:
  pull_request_target:
    types: [labeled]
  workflow_dispatch:


jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:14
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: build
        run: npm run ci-build

      - name: lint
        run: npm run lint
  
